name: MassTransit-Demo-workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_FILE_PATH: "./MassTransit-SQS/MassTransit-SQS.sln"
  PUBLISH_APP_PATH: "../publish"

jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore '{{ SOLUTION_FILE_PATH }}'

    - name: Build
      run: dotnet build '{{ SOLUTION_FILE_PATH }}' --no-restore --configuration Release

    - name: Publish
      run: dotnet publish '{{ SOLUTION_FILE_PATH }}'  --configuration Releasse -o '{{ PUBLISH_APP_PATH }}'
